name: country_state_picker
description: A Package for Selecting Countries and States from a Dropdown Field. Compactible with IOS,ANDROID AND WEB. Feel free to make PR's and suggestions.
version: 0.0.5
homepage: https://github.com/iamevansobeng/country_state_picker
repository: https://github.com/iamevansobeng/country_state_picker

environment:
  sdk: ">=2.16.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  assets:
    - lib/utils/
